### ISSUE TITLE
[Bug] Crashing when printing text

### ISSUE THREAD

**Issue by MrIkso** [Rosemoe/CodeEditor#21]
Crashing when printing text 
`java.lang.IndexOutOfBoundsException: Index: 4, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at io.github.rosemoe.editor.widget.CodeEditor.drawRows(CodeEditor.java:992)
	at io.github.rosemoe.editor.widget.CodeEditor.drawView(CodeEditor.java:838)
	at io.github.rosemoe.editor.widget.CodeEditor.onDraw(CodeEditor.java:3263)
	at android.view.View.draw(View.java:23191)
	at android.view.View.updateDisplayListIfDirty(View.java:22066)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
	at android.view.View.updateDisplayListIfDirty(View.java:22021)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
	at android.view.View.updateDisplayListIfDirty(View.java:22021)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
	at android.view.View.updateDisplayListIfDirty(View.java:22021)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
	at android.view.View.updateDisplayListIfDirty(View.java:22021)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4267)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4051)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3324)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2204)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9003)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
`

**Comment by Rosemoe** [comment]
Which layout are you using? Are you using wordwrap?

**Comment by MrIkso** [comment]
> Which layout are you using? Are you using wordwrap?

No, I'm not using wordwrap

**Comment by Rosemoe** [comment]
> No, I'm not using wordwrap
What about #24 and #23 ?

**Comment by MrIkso** [comment]
Video from #23 
https://drive.google.com/file/d/1IpGcS5OmzYtlGKB9EgU8O87e16N3ds67/view?usp=drivesdk

**Comment by Rosemoe** [comment]
Is there anything special happened before this exception?
Such as typing quickly.

**Comment by MrIkso** [comment]
this will happen if you enter some invalid text for the selected language.

**Comment by Rosemoe** [comment]
Emmmm. How to reproduce this in Java language?

**Comment by Rosemoe** [comment]
This problem is probably not caused by bad characters in language.
It is more likely to be caused by a recycling process.
While painting is in progress, the recycler recycled the spans in the list and cause the problem.
