### ISSUE TITLE
uncaughtException java.lang.AbstractMethodError when install the signed APK of sample app

### ISSUE THREAD

**Issue by RandunuK** [Rosemoe/CodeEditor#48]
I'm getting the following exception when install the signed APK of the sample app.

```2021-04-08 14:04:24.705 2401-2401/? E/XXTAG: uncaughtException: 
    java.lang.AbstractMethodError: abstract method "io.github.rosemoe.editor.widget.SymbolPairMatch io.github.rosemoe.editor.interfaces.EditorLanguage.getSymbolPairs()"
        at io.github.rosemoe.editor.widget.CodeEditor.setEditorLanguage(CodeEditor.java:635)
        at io.github.rosemoe.editor.app.MainActivity.onCreate(MainActivity.java:95)
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by itsaky** [comment]
I think this happens due to unimplemented ```getSymbolPairs``` method in JavaLanguage.

The ```JavaLanguage``` class should implement ```getSymbolPairs``` interface method and at least return null. Doing so, the error is fixed.

**Comment by RandunuK** [comment]
> I think this happens due to unimplemented `getSymbolPairs` method in JavaLanguage.
> 
> The `JavaLanguage` class should implement `getSymbolPairs` interface method and at least return null. Doing so, the error is fixed.

yep, this will fix the issue.

```
@Override
    public SymbolPairMatch getSymbolPairs() {
        return new SymbolPairMatch.DefaultSymbolPairs();
    }
```

**Comment by itsaky** [comment]
I think this can be closed now...

**Comment by Rosemoe** [comment]
I reproduced this on Android Lollipop. The problem seems to be caused by low Android version. Default methods are supported after Android N. I'll remove default modifiers and implement them in subclasses.
