### ISSUE TITLE
输入(){}后，在花括号中间按回车再按回退键，崩溃日志

### ISSUE THREAD

**Issue by xiaoyvyv** [Rosemoe/CodeEditor#7]
```java
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:954)
        at java.lang.StringBuilder.substring(StringBuilder.java:77)
        at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:900)
        at java.lang.StringBuilder.substring(StringBuilder.java:77)
        at io.github.rosemoe.editor.text.Content.subContent(Content.java:528)
        at io.github.rosemoe.editor.text.Content.subSequence(Content.java:129)
        at io.github.rosemoe.editor.widget.EditorInputConnection.getTextRegionInternal(EditorInputConnection.java:115)
        at io.github.rosemoe.editor.widget.EditorInputConnection.getTextRegion(EditorInputConnection.java:124)
        at io.github.rosemoe.editor.widget.EditorInputConnection.getTextAfterCursor(EditorInputConnection.java:141)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:255)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:94)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7053)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Comment by Rosemoe** [comment]
本问题是由于CachedIndexer中push()方法的不正确操作导致其子类NoCacheIndexer中意外存在了无限制的缓存,并且不会在文本更新时跟随一起更新,导致EditorInputConnection,CodeEditor中获取的index错误,从而导致了删除文本,获取文本以及选择文本时的几率崩溃.
现在已经修复了此问题.
